#!/usr/bin/env php
<?php

ini_set('display_errors', 1);
error_reporting(E_ALL);
ini_set('memory_limit','2G');
$now = new \DateTime('now');
ini_set(
        'error_log',
        sprintf(
        '%s/tmp/log/%s.log',
        __DIR__,
        $now->format('Ymd')
));

require_once('vendor/autoload.php');
require_once('bootstrap.php');


use App\Console\Command\ImportNewsletter;
use Console\Command\ImportUpgrade;
use Symfony\Component\Console\Application;
use Console\Helper\Log as LogHelper;

try {
    $application = new Application();
    $application->add(new ImportUpgrade());
    $application->add(new ImportNewsletter());
    $application->run();

} catch (\Exception $e) {
    print_r($e->getMessage());
    $log = new LogHelper();
    $log->error(sprintf(
        $e->getMessage()
    ), $e);

}
