CREATE TABLE `raw_reservation_res` (
  `reservation_id` int(11) NOT NULL,
  `portal_id` int(11) DEFAULT NULL,
  `structure_id` int(11) DEFAULT NULL,
  `partner_id` int(11) DEFAULT NULL,
  `guest_id` int(11) DEFAULT NULL,
  `reservation_type` tinyint(3) unsigned DEFAULT NULL,
  `reservation_number` varchar(25) DEFAULT NULL,
  `reservation_name` varchar(100) DEFAULT NULL,
  `reservation_surname` varchar(100) DEFAULT NULL,
  `reservation_company` varchar(100) DEFAULT NULL,
  `reservation_email` varchar(100) DEFAULT NULL,
  `reservation_city` varchar(50) DEFAULT NULL,
  `reservation_state` varchar(50) DEFAULT NULL,
  `reservation_zipcode` varchar(50) DEFAULT NULL,
  `reservation_country` varchar(100) DEFAULT NULL,
  `reservation_guest_language` varchar(10) DEFAULT NULL,
  `reservation_newsletter_language` char(2) DEFAULT NULL,
  `reservation_checkin_date` date DEFAULT NULL,
  `reservation_checkout_date` date DEFAULT NULL,
  `reservation_numpersons` tinyint(4) DEFAULT NULL,
  `reservation_numnights` tinyint(4) DEFAULT NULL,
  `reservation_numrooms` tinyint(4) DEFAULT NULL,
  `reservation_tot_reservation_price` float(20,3) DEFAULT NULL,
  `reservation_tot_account` float(20,2) DEFAULT NULL,
  `reservation_payment_within_day` date DEFAULT NULL,
  `reservation_payment_type` char(2) DEFAULT NULL,
  `reservation_status` tinyint(4) DEFAULT NULL,
  `reservation_opened_date` datetime DEFAULT NULL,
  `reservation_deleted` tinyint(3) unsigned DEFAULT NULL,
  `reservation_origin` char(1) DEFAULT NULL,
  `reservation_assurance_type` tinyint(4) DEFAULT NULL,
  `reservation_assurance_status` tinyint(4) DEFAULT NULL,
  `reservation_expiration_date` datetime DEFAULT NULL,
  `reservation_update_allotment` tinyint(4) DEFAULT NULL,
  `sync_code` varchar(100) DEFAULT NULL,
  `sync_timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`reservation_id`),
  KEY `sync_timestamp` (`sync_timestamp`),
  KEY `reservation_opened_date` (`reservation_opened_date`),
  KEY `sync_code` (`sync_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
