CREATE TABLE `dm_reservation_res` (
  `sync_code` varchar(100) NOT NULL,
  `structure_uid` varchar(100) NOT NULL,
  `structure_name` varchar(100) DEFAULT NULL,
  `structure_status` int(2) DEFAULT NULL,
  `portal_uid` varchar(100) DEFAULT NULL,
  `portal_name` varchar(100) DEFAULT NULL,
  `opened_date` date DEFAULT NULL,
  `opened_day` int(4) DEFAULT NULL,
  `opened_month` int(4) DEFAULT NULL,
  `opened_year` int(4) DEFAULT NULL,
  `opened_week` int(4) DEFAULT NULL,
  `opened_weekend` tinyint(1) DEFAULT NULL,
  `opened_weekday` int(4) DEFAULT NULL,
  `checkin_date` date DEFAULT NULL,
  `checkin_day` int(4) DEFAULT NULL,
  `checkin_month` int(4) DEFAULT NULL,
  `checkin_year` int(4) DEFAULT NULL,
  `checkin_week` int(4) DEFAULT NULL,
  `checkin_weekend` tinyint(1) DEFAULT NULL,
  `checkin_weekday` int(4) DEFAULT NULL,
  `checkout_date` date DEFAULT NULL,
  `checkout_day` int(4) DEFAULT NULL,
  `checkout_month` int(4) DEFAULT NULL,
  `checkout_year` int(4) DEFAULT NULL,
  `checkout_week` int(4) DEFAULT NULL,
  `checkout_weekend` tinyint(1) DEFAULT NULL,
  `checkout_weekday` int(4) DEFAULT NULL,
  `nights` int(4) DEFAULT NULL,
  `price` float(20,3) DEFAULT NULL,
  `room_code` varchar(13) DEFAULT NULL,
  `treatment` varchar(13) DEFAULT NULL,
  `pax` varchar(40) DEFAULT NULL,
  `paxtype` varchar(40) DEFAULT NULL,
  `adults` int(4) DEFAULT NULL,
  `children` int(4) DEFAULT NULL,
  `infantes` int(4) DEFAULT NULL,
  `babies` int(4) DEFAULT NULL,
  `kids` int(4) DEFAULT NULL,
  `teens` int(4) DEFAULT NULL,
  `noset` int(4) DEFAULT NULL,
  `dba` int(11) DEFAULT NULL,
  `lead_time` varchar(30) DEFAULT NULL,
  `adr` float(20,3) DEFAULT NULL,
  `rev_x_pax` float(20,3) DEFAULT NULL,
  `status` varchar(60) DEFAULT NULL,
  `status_group` varchar(60) DEFAULT NULL,
  `origin` varchar(30) DEFAULT NULL,
  `original_type` varchar(30) DEFAULT NULL,
  `type` varchar(30) DEFAULT NULL,
  `rate_code` varchar(30) DEFAULT NULL,
  `rate` varchar(200) DEFAULT NULL,
  `guests` int(11) DEFAULT NULL,
  `country` varchar(100) DEFAULT NULL,
  `country_iso2` varchar(4) DEFAULT NULL,
  `country_iso3` varchar(4) DEFAULT NULL,
  `country_type` varchar(20) DEFAULT NULL,
  `sync_timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`sync_code`,`structure_uid`),
  KEY `sync_timestamp` (`sync_timestamp`),
  KEY `checkin_date` (`checkin_date`),
  KEY `checkin_month` (`checkin_month`),
  KEY `checkin_year` (`checkin_year`),
  KEY `checkout_date` (`checkout_date`),
  KEY `checkout_month` (`checkout_month`),
  KEY `checkout_year` (`checkout_year`),
  KEY `opened_date` (`opened_date`),
  KEY `opened_month` (`opened_month`),
  KEY `opened_year` (`opened_year`),
  KEY `country` (`country`),
  KEY `origin` (`origin`),
  KEY `type` (`type`),
  KEY `original_type` (`original_type`),
  KEY `status` (`status`),
  KEY `status_group` (`status_group`),
  KEY `country_type` (`country_type`),
  KEY `structure_uid` (`structure_uid`),
  KEY `structure_name` (`structure_name`),
  KEY `structure_status` (`structure_status`),
  KEY `portal_uid` (`portal_uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
/*!50100 PARTITION BY KEY (structure_uid)
PARTITIONS 1000 */;
